server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
        - id: userCmdApi-RegisterUser
          uri: http://localhost:8084/api/v1/registerUser
          predicates:
            - Path=/api/v1/registerUser

        - id: userCmdApi-UpdateUser
          uri: http://localhost:8084/api/v1/updateUser/**
          predicates:
            - Path=/api/v1/updateUser/**

        - id: userCmdApi-RemoveUser
          uri: http://localhost:8084/api/v1/removeUser/**
          predicates:
            - Path=/api/v1/removeUser/**

        - id: userQueryApi
          uri: http://localhost:8085/api/v1/userLookup/**
          predicates:
            - Path=/api/v1/userLookup/**

        - id: bankAccCmdApi-OpenAccount
          uri: http://localhost:9071/api/v1/openBankAccount
          predicates:
            - Path=/api/v1/openBankAccount

        - id: bankAccCmdApi-DepositFunds
          uri: http://localhost:9071/api/v1/depositFunds/**
          predicates:
            - Path=/api/v1/depositFunds/**

        - id: bankAccCmdApi-WithdrawFunds
          uri: http://localhost:9071/api/v1/withdrawFunds/**
          predicates:
            - Path=/api/v1/withdrawFunds/**

        - id: bankAccCmdApi-CloseAccount
          uri: http://localhost:9071/api/v1/closeBankAccount/**
          predicates:
            - Path=/api/v1/closeBankAccount/**

        - id: bankAccQueryApi
          uri: http://localhost:9072/api/v1/bankAccountLookup/**
          predicates:
            - Path=/api/v1/bankAccountLookup/**

